apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
   name: example-kc
spec:
   instances: 1
   serverConfiguration:
   - name: db
     value: postgres
   - name: db-url-host
     value: hippo-primary
   - name: db-username
     secret:
       name: hippo-pguser-hippo
       key: user
   - name: db-password
     secret:
       name: hippo-pguser-hippo
       key: password
   - name: db-url
     secret:
       name: hippo-pguser-hippo
       key: jdbc-uri
   http:
     httpEnabled: true
     httpPort: 80
     httpsPort: 443
     tlsSecret: example-tls-secret
   hostname:
     hostname: example-kc-service-postgres1.apps.ocp2ipi.ntnxlab.local 
     strict: false
     strictBackchannel: false
