apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
   name: example-kc
spec:
   instances: 1
   serverConfiguration:
   - name: db
     value: postgres
   - name: db-url-host
     value: hippo-primary
   - name: db-username
     secret:
       name: hippo-pguser-hippo
       key: user
   - name: db-password
     secret:
       name: hippo-pguser-hippo
       key: password
   - name: db-url
     secret:
       name: hippo-pguser-hippo
       key: jdbc-uri
   http:
   #  tlsSecret: example-tls-secret
     httpEnabled: true
     httpPort: 80
   hostname:
   #  hostname: test.keycloak.org
     strict: false
     strictBackchannel: false
